### ISSUE TITLE
DynamoDB client.get_item Key parameter has incorrect type hint

### ISSUE THREAD

**Issue by brent-moffit** [youtype/mypy_boto3_builder#146]
**Describe the bug**
in `mypy_boto3_dynamodb/client.py` the `get_item` function definition uses this type hit for `Key`:
```python
        Key: Mapping[
            str,
            Union[
                bytes,
                bytearray,
                str,
                int,
                Decimal,
                bool,
                Set[int],
                Set[Decimal],
                Set[str],
                Set[bytes],
                Set[bytearray],
                Sequence[Any],
                Mapping[str, Any],
                None,
            ],
```

The [boto3 documentation goes into great detail on the format of key](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Client.get_item), but for brevity here is the example they provide:
```python
response = client.get_item(
    Key={
        'Artist': {
            'S': 'Acme Band',
        },
        'SongTitle': {
            'S': 'Happy Day',
        },
    },
    TableName='Music',
)
```

So the correct structure for `Key` should be as follows (with the nested `Mapping` added):
```python
        Key: Mapping[
            str,
            Mapping[
                str,
                Union[
                    bytes,
                    bytearray,
                    str,
                    int,
                    Decimal,
                    bool,
                    Set[int],
                    Set[Decimal],
                    Set[str],
                    Set[bytes],
                    Set[bytearray],
                    Sequence[Any],
                    Mapping[str, Any],
                    None,
            ]
```

**To Reproduce**

1. Install `boto3-stubs["dynamodb"]`
2. View `mypy_boto3_dynamodb/client.py::get_item` and compare to [docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Client.get_item)

**Additional context**
MacOS 12.3.1 (ARM), `boto3 == 1.22.8`, `botocore == 1.25.8`, `boto3-stubs == 1.22.8`

**Comment by vemel** [comment]
Hello! Thank you for the report!

This issue is related to #144 . Looks like `boto3` used to wrap `botocore.dynamodb` methods to convert attributes from `{"type": "value"}` to `python` data types. However, now `boto3` does not do this anymore. 

I have already added the necessary changes to `main`. I have to cross-check everything and release a new version. Hopefully today.

**Comment by milanboers** [comment]
@vemel I don't think they ever did this on the [Client](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#client) methods. They do it on the [Table](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#table) methods though.

Perhaps not 100% related to this issue, but the `Mapping[str, ...]` type for `{"S": "..."}` would cause some issues with `TypeDeserializer`. I think it's common that people would pass the outcome of `batch_get_item` etc. to the `TypeDeserializer`. `TypeDeserializer` currently requires `Mapping[Literal["S"] | ...]]` and passing a `Mapping[str, ..]` would fail type checking.

**Comment by vemel** [comment]
I have released `7.5.10` with a proper fix. However, I have not checked `TypeDeserializer`. What would be a proper solution? Probably we can always use `List` instead of `Sequence` and `Dict` instead of `Mapping`. I will check if I can do this only for output structures.

**Comment by vemel** [comment]
@milanboers this should also fix `TypeDeserializer` usage: https://github.com/youtype/mypy_boto3_builder/releases/tag/7.5.11

**Comment by milanboers** [comment]
@vemel I think the current `main` fixes it for `Client` but breaks it for `Table`/`ServiceResource`. The `Table`/`ServiceResource` are "higher-level" and map to python types, while `Client` returns `{"S"...}` etc.

See for example [get_item on Client](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Client.get_item) and [get_item on Table](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Table.get_item)

Both are annotated with `GetItemOutputTypeDef` now.

**Comment by vemel** [comment]
Fixed in the latest `boto3-stubs` release. @brent-moffit , @milanboers  please let me know if it works as it should.

**Comment by milanboers** [comment]
The return types seem good to me @vemel . Thanks!

I'm only still having issues with passing the results to `TypeDeserializer.deserialize` because:
- Input parameter `value: Dict[DynamoDBDataType, Any]` takes a `Dict` which is not compatible with the `TypedDict` returned by the `Client` methods. Could be solved by changing it into a `Mapping`.
- The keys of the `AttributeValueTypeDef` can't be assigned to `DynamoDBDataType` (assigning `str` to `Literal[..]`), at least in Pyright. I guess there's little you can do about this except making the whole argument `value: Mapping[str, Any]`, and that would make it a lot less useful when constructing the argument manually 😅

**Comment by vemel** [comment]
@milanboers 
Please try updating to `boto3-stubs 1.22.8.post1`. `deserialize` now accepts `Mapping[DynamoDBDataType, Any]`. 

Indeed, passing `client.get_item(...)["Item"]` output to `TypeDeserializer.deserialize` does not work. The proper solution would be to accept a `TypedDict` instead of a `Mapping`. THen you will still have issues with raw `dict` input, but should work correctly with `client` return types.

**Comment by milanboers** [comment]
Looks good :) Personally I don't mind adding a `# type: ignore` to cases like this, but I think most people would be using `deserialize` with return types rather than manually constructed dicts anyway.

**Comment by vemel** [comment]
New `boto3-stubs` is out with the fix for `TypeDeserializer`. Please let me know if it works as it should for you.

**Comment by milanboers** [comment]
Works great for me! Thanks a lot!

**Comment by brent-moffit** [comment]
Agreed, the fix is working great and the fast turn-around was fantastic!
