### ISSUE TITLE
AIOBoto3ServiceResource needs to inherit from contextlib.AbstractAsyncContextManager

### ISSUE THREAD

**Issue by tibbe** [youtype/mypy_boto3_builder#185]
**Describe your idea**
`AIOBoto3ServiceResource` needs to inherit from the standard library's `contextlib.AbstractAsyncContextManager` such that it can be used with the standard library facilities for async context managers, such as `contextlib.AsyncExitStack`, and still type check correctly.

`AsyncExitManager` is useful when you can't scope resource acquisition and release with a `with` statement, such as when you want to set up client connections at import time, which is what you need to do if you want to benefit from AWS Lambda provisioned concurrency.

**Code sample**
Currently type checking works for

```python
async with session.resource('dynamodb') as dynamo_resource:
    ...
```

but the following fails

```
exit_stack = contextlib.AsyncExitStack()
dynamodb = await exit_stack.enter_async_context(session.resource('dynamodb'))
```

with the following type error:

```
Argument 1 to "enter_async_context" of "AsyncExitStack" has incompatible type "DynamoDBServiceResource"; expected "AbstractAsyncContextManager[<nothing>]"  [arg-type]mypy(error)
```

I believe this is due to `AIOBoto3ServiceResource` and thus by extension `DynamoDBServiceResource` not implementing `AbstractAsyncContextManager`, despite actually having the right `__aenter__` and `__aexit__` methods.

The type of `enter_async_context` is

```python
def enter_async_context(cm: AbstractAsyncContextManager[_T@enter_async_context]) -> Coroutine[Any, Any, _T@enter_async_context]
```

**Additional context**

Versions:
```
boto3 = "1.24.59"
botocore = "1.27.59"
boto3-stubs = {version = "1.24.59", extras = ["apigatewaymanagementapi", "cloudsearch", "cloudsearchdomain", "cognito-idp", "dynamodb", "s3", "secretsmanager", "ses", "sns", "sqs", "transcribe", "translate"]}
aioboto3 = "^10.4.0"
types-aioboto3 = {version = "10.4.0", extras = ["dynamodb"]}
types-aiobotocore = "2.4.2"
```

**Comment by vemel** [comment]
`AIOBoto3ServiceResource` itself does not inherit `contextlib.AbstractAsyncContextManager`. So looks like it could potentially lead to incorrect type annotations. Could you please check if `aioboto3` code works as expected with `AsyncExitStack`?

```python
exit_stack = contextlib.AsyncExitStack()
dynamodb = await exit_stack.enter_async_context(session.resource('dynamodb'))
```

**Comment by tibbe** [comment]
The code example you gave is the one I tested (see my initial comment). It runs OK but doesn't type check. `AIOBoto3ServiceResource` needs to inherit from `contextlib.AbstractAsyncContextManager`

**Comment by vemel** [comment]
I found the issue. Typing was incompatible with `AbstractAsyncContextManager`, but an inheritance from it is not required. Fixed `ServiceResource`, `dynamodb.Table` and `dynamodb.Query` classes. I will prepare a new release by tomorrow.

**Comment by vemel** [comment]
@tibbe Fixed in `types-aioboto3 11.0.1.post1`. Please test the new release and let me know if it works as expected.

**Comment by tibbe** [comment]
Thanks!

Looking into it now. A first nit is that I think the traceback type should be `Optional[TracebackType]` rather than `Any`. Validating the rest now.

**Comment by tibbe** [comment]
Seems to still not work (unless I'm holding it wrong):

```python
async def test() -> None:
    exit_stack = contextlib.AsyncExitStack()
    session = aioboto3.Session()
    dynamodb: DynamoDBServiceResource = await exit_stack.enter_async_context(
        session.resource('dynamodb'))
```

```
note: Following member(s) of "DynamoDBServiceResource" have conflicts:
note:     Expected:
note:         def __aexit__(self, Optional[Type[BaseException]], Optional[BaseException], Optional[TracebackType], /) -> Coroutine[Any, Any, Optional[bool]]
note:     Got:
note:         def __aexit__(self, exc_type: Type[BaseException], exc_value: BaseException, exc_tb: Any) -> Coroutine[Any, Any, None]
```

There's a difference in the traceback type and the return type (`None` vs `Optional[Bool]`).

**Comment by vemel** [comment]
Thank you for testing. I do not use `TracebackType` because stubs had to be compatible with `py36`. Py36 is no longer supported, so I can actually use this type. Closing the issue.
